//constants for the rest of the app
const ADD_POINT = 'ADD POINT';
const INSERT_NODE = 'INSERT NODE';
const SET_ROOT = 'SET_ROOT';
const CLEAR_POINTS = 'CLEAR POINTS';
const CLEAR_NODE = 'CLEAR NODE';
const REBALANCE = 'REBALANCE';
const CLEAR_SATISFIERS = 'CLEAR SATISFIERS';

export {ADD_POINT, INSERT_NODE, SET_ROOT, CLEAR_POINTS, CLEAR_NODE, REBALANCE, CLEAR_SATISFIERS};
